In [1]:
import numpy as np
import scipy
from numpy import mean, absolute
import pandas as pd
from sklearn import *

from scipy import spatial
from sklearn.metrics.pairwise import euclidean_distances
from scipy.spatial import distance
import math
from sklearn.decomposition import PCA 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from itertools import chain
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

from os import listdir
from pathlib import Path
from os.path import isfile, join
from natsort import natsorted ## !pip install natsort

In [2]:
xtrainFileName="xtrain_AWID_FeatureSelection_reduced.npy"
xtestFileName="xtest_AWID_FeatureSelection_reduced.npy"
ytrainFileName="ytrain_AWID_FeatureSelection_reduced.npy"
ytestFileName="ytest_AWID_FeatureSelection_reduced.npy"
X_train=np.load(xtrainFileName)
X_test=np.load(xtestFileName)
y_train=np.load(ytrainFileName)
y_test=np.load(ytestFileName)

In [3]:
X_test

array([[-0.57573164, -0.19466678,  0.57611728, ..., -0.04813688,
        -0.97198544, -0.55207137],
       [-0.43783856, -0.29087712, -0.09255321, ..., -0.28251807,
         1.05597342, -0.48071656],
       [-0.32292766,  2.5879669 , -0.09255321, ..., -0.14188935,
         1.05597342, -0.62342618],
       ...,
       [-0.32292766,  2.81718908, -0.09255321, ..., -0.23564183,
         1.05597342, -1.26561948],
       [ 1.92275963, -0.45678132, -0.04894427, ...,  2.14332723,
         1.05597342,  1.01773447],
       [-0.39844054, -0.28926337, -0.06389591, ..., -0.25907995,
         1.05597342, -0.76613581]])

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [5]:
scaler=StandardScaler().fit(X_train)
X_train_transformed=scaler.transform(X_train)
X_test_transformed=scaler.transform(X_test)

In [6]:
X_train_transformed

array([[-0.57244847, -0.83217363, -0.07427899, ..., -0.47002302,
        -0.97198544, -0.76613581],
       [-0.60199699, -0.01866551, -0.09213789, ..., -0.47002302,
        -0.97198544, -1.4083291 ],
       [-0.60199699,  0.04429943, -0.08009351, ..., -0.28251807,
        -0.97198544,  0.51825079],
       ...,
       [ 1.82754774, -0.64503608, -0.07012576, ...,  0.46750174,
         1.05597342,  1.01773447],
       [ 1.87679527, -0.79560333,  0.04035024, ...,  0.67844481,
         0.37998714,  1.08908928],
       [-0.45753757, -0.63329279, -0.04146845, ..., -0.28251807,
         1.05597342, -0.76613581]])

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import itertools
import matplotlib.pyplot as plt
from scipy.stats import mode
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV
import time

In [8]:
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier

In [9]:
from sklearn.preprocessing import OneHotEncoder

y_train_df = pd.DataFrame(y_train)
y_test_df = pd.DataFrame(y_test)

#onehotencoder1 = OneHotEncoder(categorical_features = [0])
#y_train = onehotencoder1.fit_transform(y_train).toarray()
#y_test = onehotencoder1.fit_transform(y_test).toarray()


#y_train.
#y_test.shape

In [10]:


encoder = OneHotEncoder(sparse=False)
y_train = encoder.fit_transform(y_train_df)
y_test = encoder.fit_transform(y_test_df)



In [11]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [12]:
import tensorflow as tf
keras = tf.keras  
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.optimizers import Adam
from keras.initializers import Constant
from keras.callbacks import LearningRateScheduler

In [13]:
model = Sequential()
model.add(Conv1D(filters=64,kernel_size=3,
    strides=1,activation='relu', padding = 'same', input_shape=(X_train.shape[1], 1),name='Input'))
model.add(Dense(128, input_dim=X_train.shape[1], name='Dense_0', 
                #kernel_initializer='he_uniform', 
                 activation='PReLU'))
model.add(MaxPooling1D(2))
model.add(Dense(64, activation='PReLU', name='Dense_1'))
model.add(Dense(32, activation='PReLU',name='Dense_2'))
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(y_train.shape[1], activation='softmax', name='Output'))


In [14]:
X_train_transformed = X_train_transformed[:, :, np.newaxis]
X_test_transformed = X_test_transformed[:, :, np.newaxis]

In [18]:
import math

k1=10
n1=X_train.shape[1]
n2=n1-k1+1
n3=4
k2=math.ceil(n2/n3)
n4=100

#model_name=(dataset+'_1DCNN')
model = Sequential()

model.add(Conv1D(k1, n2, activation='relu', padding = 'same', input_shape=(X_train.shape[1], 1)))
#model.add(layers.Conv1D(128, 5, activation='relu', padding = 'same'))
model.add(MaxPooling1D(n3))
model.add(Dense(n4, activation='relu'))
model.add(Flatten())
model.add(Dense(y_train.shape[1], activation='softmax'))

#model.add(layers.Conv1D(128, 5, activation='relu', padding = 'same'))
#model.add(layers.Conv1D(128, 5, activation='relu', padding = 'same'))
#model.add(layers.MaxPooling1D(2))
#
#model.add(layers.Flatten())
#
#model.add(layers.Dense(128, activation='relu'))
#model.add(layers.Dropout(0.5))
#model.add(layers.Dense(128, activation='relu'))
#model.add(layers.Dropout(0.5))
#model.add(layers.Dense(128, activation='relu'))
#model.add(layers.Dropout(0.5))
#
#model.add(layers.Dense(y_train.shape[1], activation='softmax'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_1 (Conv1D)           (None, 19, 10)            110       
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 4, 10)            0         
 1D)                                                             
                                                                 
 dense (Dense)               (None, 4, 100)            1100      
                                                                 
 flatten_1 (Flatten)         (None, 400)               0         
                                                                 
 dense_1 (Dense)             (None, 14)                5614      
                                                                 
Total params: 6,824
Trainable params: 6,824
Non-trainable params: 0
____________________________________________________

In [19]:
sd=[]
class LossHistory(keras.callbacks.Callback):
    def on_train_begin(self, logs={}):
        self.losses = [1,1]

    def on_epoch_end(self, batch, logs={}):
        self.losses.append(logs.get('loss'))
        sd.append(step_decay(len(self.losses)))
        print('lr:', step_decay(len(self.losses)))

In [20]:
#learning_rate = 0.1
#decay_rate = 5e-6
#momentum = 0.9
#epochs=100
from tensorflow.keras.callbacks import LearningRateScheduler, ModelCheckpoint, ReduceLROnPlateau

filepath='WNIDS_CNN_model_projec_FS.hdf5'

reduce_lr = ReduceLROnPlateau(monitor="loss", factor=0.3, patience=50, verbose=1, cooldown=10, min_lr=1e-5)
lr_shceduler = LearningRateScheduler(lambda _, lr: lr * np.exp(-0.01), verbose=1)
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')


In [21]:
def step_decay(losses):
    if float(2*np.sqrt(np.array(history.losses[-1])))<0.3:
        lrate=0.01*1/(1+0.1*len(history.losses))
        momentum=0.8
        decay_rate=2e-6
        return lrate
    else:
        lrate=0.1
        return lrate

In [22]:
#history=LossHistory()
#lrate=LearningRateScheduler(step_decay)

In [23]:
callbacks = [reduce_lr, lr_shceduler,checkpoint]

In [24]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
#optimizer=Adam(lr=lr_schedule(0))
#optimizer='rmsprop'
model.compile(optimizer, 
              #loss='binary_crossentropy',
              loss='categorical_crossentropy', 
              #loss='mse', 
              metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())



Neural Network Model Summary: 
Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_1 (Conv1D)           (None, 19, 10)            110       
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 4, 10)            0         
 1D)                                                             
                                                                 
 dense (Dense)               (None, 4, 100)            1100      
                                                                 
 flatten_1 (Flatten)         (None, 400)               0         
                                                                 
 dense_1 (Dense)             (None, 14)                5614      
                                                                 
Total params: 6,824
Trainable params: 6,824
Non-trainable params: 0
_____________________

C:\Users\sanjay\anaconda3\envs\Projects_Segmentation\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
# Train the model
start = time.time()
model_history=model.fit(X_train_transformed, y_train, 
          verbose=1, 
          batch_size=128, 
          epochs=100, 
          validation_split=0.1,
          callbacks=callbacks
          #validation_data=(X_test, y_test)
                       )
end = time.time()
print('Time elapsed: %.4f'%(end-start))



Epoch 00001: LearningRateScheduler setting learning rate to 0.0009900498807740119.
Epoch 1/100
11684/11696 [============================>.] - ETA: 0s - loss: 0.0527 - accuracy: 0.9853
Epoch 00001: val_accuracy improved from -inf to 0.98992, saving model to WNIDS_CNN_model_projec_FS.hdf5
11696/11696 [==============================] - 46s 3ms/step - loss: 0.0527 - accuracy: 0.9853 - val_loss: 0.0324 - val_accuracy: 0.9899 - lr: 9.9005e-04

Epoch 00002: LearningRateScheduler setting learning rate to 0.0009801987522893801.
Epoch 2/100
11693/11696 [============================>.] - ETA: 0s - loss: 0.0281 - accuracy: 0.9907
Epoch 00002: val_accuracy improved from 0.98992 to 0.99130, saving model to WNIDS_CNN_model_projec_FS.hdf5
11696/11696 [==============================] - 39s 3ms/step - loss: 0.0281 - accuracy: 0.9907 - val_loss: 0.0268 - val_accuracy: 0.9913 - lr: 9.8020e-04

Epoch 00003: LearningRateScheduler setting learning rate to 0.0009704455922292659.
Epoch 3/100
11694/11696 [====

In [ ]:
# Test on unseen data
model.load_weights(filepath)

results = model.evaluate(X_test_transformed, y_test)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))


In [ ]:
import pandas as pd    
WNIDS_model_df = pd.DataFrame(model_history.history) 

In [ ]:
with open('WNIDS_model_cnn.csv', mode='w') as f:
    WNIDS_model_df.to_csv(f)   





In [ ]:
history_model = model_history

#plot the training and validation accuracy and loss at each epoch
loss = history_model.history['loss']
val_loss = history_model.history['val_loss']
epochs = range(1, len(loss) + 1)
plt.plot(epochs, loss, 'y', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

acc = history_model.history['accuracy']
#acc = history.history['accuracy']
val_acc = history_model.history['val_accuracy']
#val_acc = history.history['val_accuracy']

plt.plot(epochs, acc, 'y', label='Training accuracy')
plt.plot(epochs, val_acc, 'r', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()




In [ ]:

predictions1=model.predict(X_test_transformed)
predictions1 = predictions1.argmax(axis=-1)
y_test=y_test.argmax(axis=-1)
accuracy_model1=accuracy_score(y_test,predictions1)
print("The accuray after the first classifier (4 classes)is: ")
print(accuracy_model1)
cm0=confusion_matrix(y_test,predictions1)
cm0





In [ ]:
classes=['Normal', 'Deauth', 'Disas', '(Re)Assoc',
                            'RogueAP', 'Krack', 'Kr00k',
                            'SSH', 'Botnet', 'Malware', 'SQL_Injection',
                            'SSDP','Evil_Twin', 'Website_spoofing']

In [ ]:
fig = plt.figure(figsize=(36,16))
plt.imshow(cm0, interpolation='nearest', cmap=plt.cm.Blues)
plt.colorbar()
tick_marks = np.arange(len(classes))
plt.xticks(tick_marks, classes, rotation=45)
plt.yticks(tick_marks, classes)

fmt = 'd'
np.set_printoptions(precision=2)
thresh = cm0.max() / 2.
for i, j in itertools.product(range(cm0.shape[0]), range(cm0.shape[1])):
    plt.text(j, i, format(cm0[i, j], fmt), size=16,
             horizontalalignment="center", color="white" if cm0[i, j] > thresh else "black")
    plt.tight_layout()
    plt.ylabel('True label', fontweight='bold')
    plt.xlabel('Predicted label', fontweight='bold')
   
plt.show()
fig.savefig('confusion_matrix_4_classes_2.png',dpi=600)



In [ ]:
cr0 = classification_report(y_test, predictions1, target_names=classes)
print(cr0)
accuracy_0 = accuracy_score(y_test, predictions1)*100
print("The accuray after the first classifier (4 classes)is: ",accuracy_0,"%")




In [ ]:
#from keras_visualizer import visualizer 
#visualizer(model, format='png', view=True)


In [ ]:
from operator import truediv
def AA_andEachClassAccuracy(confusion_matrix):
    counter = confusion_matrix.shape[0]
    list_diag = np.diag(confusion_matrix)
    list_raw_sum = np.sum(confusion_matrix, axis=1)
    each_acc = np.nan_to_num(truediv(list_diag, list_raw_sum))
    average_acc = np.mean(each_acc)
    return each_acc, average_acc

In [ ]:
each_acc, av_acc=AA_andEachClassAccuracy(cm0)

In [ ]:
each_acc